--- 
title: "NYC Events Analysis"
author: "Leo Du, Hao Li"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

As Columbia students, we live in one of the most diverse and energetic cities in the world. 
The city has many interesting public places to visit - New York City has more than 1,700 parks, playgrounds, and recreation facilities across the five boroughs. 

With the large number of public facilities, there are almost always fun events happening in the city everyday.
We’re very fascinated by the different events hosted by different organizations and cultural groups here in NYC, 
and would like to explore several aspects about this topic. In particular, you can expect to learn the following 
from our analysis:

1. What are the most active and diverse parks in the New York City? Do event organizers have preferences over parks and event types?
2. What are some interesting facts of the events in the parks? Do they vary for different boroughs of the New York City?
3. Are there any seasonality and trend patterns for the events in parks? Do they vary for different event categories? 
4. Is there any association between crimes in parks and events in parks that we can identify?

We hope you'll also enjoy our study and discover new favorite parks to visit and attend public events in them!

